--
-- PostgreSQL database dump
--

-- Dumped from database version 14.15 (Ubuntu 14.15-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.15 (Ubuntu 14.15-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cars; Type: TABLE; Schema: public; Owner: carsearch_user
--

CREATE TABLE public.cars (
    length_cm integer NOT NULL,
    max_velocity_kmh integer NOT NULL,
    weight_kg integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    model character varying(100) NOT NULL,
    color character varying(255) NOT NULL,
    CONSTRAINT cars_length_cm_check CHECK ((length_cm <= 1000)),
    CONSTRAINT cars_max_velocity_kmh_check CHECK ((max_velocity_kmh <= 500)),
    CONSTRAINT cars_weight_kg_check CHECK ((weight_kg <= 10000))
);


ALTER TABLE public.cars OWNER TO carsearch_user;

--
-- Name: cars_id_seq; Type: SEQUENCE; Schema: public; Owner: carsearch_user
--

ALTER TABLE public.cars ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cars_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: carsearch_user
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


ALTER TABLE public.flyway_schema_history OWNER TO carsearch_user;

--
-- Data for Name: cars; Type: TABLE DATA; Schema: public; Owner: carsearch_user
--

COPY public.cars (length_cm, max_velocity_kmh, weight_kg, created_at, id, updated_at, model, color) FROM stdin;
495	250	2100	2024-12-28 16:06:05.312107	1	2024-12-28 16:06:05.312129	Tesla Model S	red
480	340	1435	2024-12-28 16:12:05.672536	2	2024-12-28 16:12:05.672544	Ferrari F8	red
520	250	2175	2024-12-28 16:12:24.020181	3	2024-12-28 16:12:24.020196	Mercedes S Class	black
469	261	1847	2024-12-28 16:16:31.387787	4	2024-12-28 16:16:31.387805	Tesla Model 3	white
492	243	2257	2024-12-28 16:16:38.866468	5	2024-12-28 16:16:38.866479	BMW X5	blue
463	180	1300	2024-12-28 16:16:47.994174	6	2024-12-28 16:16:47.994192	Toyota Corolla	silver
\.


--
-- Data for Name: flyway_schema_history; Type: TABLE DATA; Schema: public; Owner: carsearch_user
--

COPY public.flyway_schema_history (installed_rank, version, description, type, script, checksum, installed_by, installed_on, execution_time, success) FROM stdin;
1	1	<< Flyway Baseline >>	BASELINE	<< Flyway Baseline >>	\N	carsearch_user	2024-12-31 21:33:44.860836	0	t
\.


--
-- Name: cars_id_seq; Type: SEQUENCE SET; Schema: public; Owner: carsearch_user
--

SELECT pg_catalog.setval('public.cars_id_seq', 6, true);


--
-- Name: cars cars_pkey; Type: CONSTRAINT; Schema: public; Owner: carsearch_user
--

ALTER TABLE ONLY public.cars
    ADD CONSTRAINT cars_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: carsearch_user
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: carsearch_user
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- PostgreSQL database dump complete
--

